default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: stonksmate
  password: stonksmate
  host: localhost
  port: 5433

development:
  <<: *default
  database: stonksmate_development

test:
  <<: *default
  database: stonksmate_test

production:
  <<: *default
  database: stonksmate_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
